# Generated by Django 2.1 on 2019-06-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlarchive', '0002_auto_20190606_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['title'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
