# Generated by Django 2.2.2 on 2019-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlarchive', '0002_auto_20190606_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['title'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
