# Generated by Django 2.2.2 on 2019-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlarchive', '0004_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-link', max_length=50),
        ),
    ]
