# Generated by Django 2.1 on 2019-06-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlarchive', '0003_auto_20190606_1257'),
        ('urlarchive', '0005_auto_20190606_2000'),
    ]

    operations = [
    ]
